name: 'Generate WordPress Archive'
description: 'Generates a zip archive of a WordPress project using WP-CLI'
author: 'Linkon Miyan'
branding:
  icon: 'archive'
  color: 'green'

inputs:
  retention-days:
    description: 'How many days to keep the zip archive'
    default: 7

runs:
  using: 'composite'
  steps:
    - name: Running the action to generate zip archive
      id: archive
      run: ${{ github.action_path }}/build-zip.sh
      shell: bash

    - name: Upload the archive as an artifact
      id: upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}
        path: ./wordpress.zip
        retention-days: ${{ inputs.retention-days }}